name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Load environment variables
      run: |
        echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV
        echo "API_KEY_MESSAGE=${{ secrets.API_KEY_MESSAGE }}" >> $GITHUB_ENV
        echo "API_KEY_REACTION=${{ secrets.API_KEY_REACTION }}" >> $GITHUB_ENV

    - name: Run Tests
      run: pytest

    - name: Deploy
      run: |
        echo "Deploying using API URL $API_URL"
        # Deploy commands go here
